### PR TITLE
Fix: eliminated hardcoded URL for custom versions

### LINKED ISSUE #460: Download URL
The download URL for the server zip have changed from `https://minecraft.azureedge.net/bin-linux/bedrock-server-{VERSION}.zip` to `https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-{VERSION}.zip`

This all works fine when specifying `LATEST` or `PREVIEW` as the VERSION as it will lookup the correct URL. However when setting a specific version the URL is hardcoded to the old one.

Would it not make sense it let it use the same lookup code or perhaps even allowing setting an environment variable DOWNLOAD_URL that will take precedence if set to allow workarounds for potential future changes?

**EDIT:** It seems like the old link is now(?) working for all(?) versions except 1.21.31.04.

Thanks!

### PR DESCRIPTION
**Pull request by thedhruvn**
Old behavior: Custom versions used hardcoded download URL. this URL should be dynamically sourced using the lookupVersion command instead.

New behavior: lookupVersion takes a second parameter, version, and uses a simple sed replace to insert the version parameter into the download URL dynamically, if it was successfully found.

Also, removed old bedrock version shortcuts. This can be restored and modified to use the lookupVersion command to get the right URL if needed. It's unclear whether there's any active servers still running on legacy versions of bedrock (to this author).

Resolves #460

### CODE REVIEW

File: bedrock-entry.sh [hunk 1]
```diff
@@ -96,17 +92,13 @@ case ${VERSION^^} in
...
+    echo "Using given version ${VERSION}"
+    lookupVersion serverBedrockLinux "${VERSION}"
     ;;
 esac
 
 if [[ ! -f "bedrock_server-${VERSION}" ]]; then
 
-  if [[ -z "${DOWNLOAD_URL}" ]]; then
-    binPath=bin-linux
-    isTrue "${PREVIEW}" && binPath+="-preview"
```
Comment (itzg) [inline bedrock-entry.sh:106]: It looks like the handling of preview release's path will get lost with these changes.

**Review by itzg — COMMENTED** [review]
Thanks!

I like the overall idea of what you're doing.

However, I'm still undecided if the changes (other than old version cleanup) are needed since Microsoft seems to have corrected the one-off version location.

File: bedrock-entry.sh [hunk 2]
```diff
@@ -96,17 +92,13 @@ case ${VERSION^^} in
     ;;
   *)
     # use the given version exactly
+    echo "Using given version ${VERSION}"
+    lookupVersion serverBedrockLinux "${VERSION}"
```
Comment (thedhruvn) [inline bedrock-entry.sh:96]: @itzg I can change this to check if `${PREVIEW}` is true, then pass in `serverBedrockLinuxPreview` instead so that we don't lose the functionality you highlighted below.

**Comment by thedhruvn** [comment]
> Thanks!
> 
> I like the overall idea of what you're doing.
> 
> However, I'm still undecided if the changes (other than old version cleanup) are needed since Microsoft seems to have corrected the one-off version location.


I don't love hard-coded URLs in general - my suggestion would be to adopt this so we follow the once and only once principle in managing constants.

**Comment by itzg** [comment]
That's fair. Let's see how the preview support looks.

File: bedrock-entry.sh [hunk 3]
```diff
@@ -96,17 +92,18 @@ case ${VERSION^^} in
     ;;
   *)
     # use the given version exactly
+    if isTrue "$PREVIEW"; then
```
Comment (itzg) [inline bedrock-entry.sh:95]: There isn’t a boolean variable called PREVIEW. Instead VERSION will be set to “PREVIEW”

Comment (thedhruvn) [reply bedrock-entry.sh:95]: Hmm... isn't PREVIEW an optional variable that can be set at the environment level before executing this script? I see it above here, even if it's not actively used. I thought that was its original intention... See Lines 6/7.

```shell
: "${TMP_DIR:=/tmp}"
: "${PREVIEW:=false}"
```

Comment (thedhruvn) [reply bedrock-entry.sh:95]: The switch-case only checks the value of VERSION^^ (uppercased) and compares it to the string literal `PREVIEW`. If a user passes in `PREVIEW` instead of `LATEST`, then they will get the latest PREVIEW version. If the user instead wants a specific version, then they would just pass that version in and it would be handled by the default case. 

If the user passes in $PREVIEW=true for the environment before executing this script, then the only affect it would have is look at the `serverBedrockPreviewLinux` link on the download page for bedrock dedicated server. My understanding is that this key will find the following URL from the download page: https://www.minecraft.net/bedrockdedicatedserver/**bin-linux-preview**/bedrock-server-1.21.50.24.zip

whereas passing in `serverBedrockLinux` to the lookupVersion function will locate the following URL:
https://www.minecraft.net/bedrockdedicatedserver/**bin-linux**/bedrock-server-1.21.31.04.zip

Comment (itzg) [reply bedrock-entry.sh:95]: Ok, I'll take a closer look at the surrounding logic. 

Did you test all these variations?

Comment (itzg) [reply bedrock-entry.sh:95]: Ah, I see now what you're saying since it'll now derive from the `serverBedrockPreviewLinux` anchor.

**Review by itzg — APPROVED** [review]
These all worked correctly:

```
docker run -it --rm -e EULA=true -e VERSION=PREVIEW itzg/minecraft-bedrock-server
docker run -it --rm -e EULA=true -e VERSION=1.21.50.24 -e PREVIEW=true itzg/minecraft-bedrock-server
docker run -it --rm -e EULA=true -e VERSION=LATEST itzg/minecraft-bedrock-server
docker run -it --rm -e EULA=true -e VERSION=1.21.31.04 itzg/minecraft-bedrock-server
```
